language: python
python:
  - "3.6.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database stackoverflow;' -U postgres
addons:
  postgresql: "9.4"
script:
  - pytest --cov=.
  - coverage  
  - coveralls 
after_success:
- coveralls

  